### ISSUE TITLE
how to support chinese

### ISSUE THREAD

**Issue by crctrust** [edgaraafelix/pdfjinjax#5]
if the data value is chinese, now the package does not support。

**Comment by edgaraafelix** [comment]
Additional information is required, perhaps an example?

**Comment by crctrust** [comment]
[基金交易业务申请表-new.pdf](https://github.com/edgaraafelix/pdfjinjax/files/7115266/-new.pdf)

**Comment by crctrust** [comment]
[基金交易业务申请表-new.pdf](https://github.com/edgaraafelix/pdfjinjax/files/7115270/-new.pdf)
